// Browser-compatible YouTube transcript fetcher.
// Runs client-side so requests come from the user's residential IP,
// bypassing YouTube's block on Vercel/cloud server IPs.
//
// Flow:
//   1. POST to InnerTube player API → get caption track list
//   2. Fetch the Spanish caption track XML (caption URLs are CORS-enabled
//      because embedded YouTube players on third-party sites need them)
//   3. Parse and return normalised cues
//
// Any failure (CORS block, no captions, parse error) returns null —
// the caller falls back to the server-side /api/lyrics route (LRCLib → Genius).

const MAX_CUES = 300;

export interface RawCue {
  start: number;   // seconds
  end: number;     // seconds
  spanish: string;
}

interface CaptionTrack {
  languageCode: string;
  baseUrl: string;
  kind?: string; // "asr" = auto-generated by YouTube
}

export async function fetchYouTubeTranscriptClientSide(
  videoId: string
): Promise<RawCue[] | null> {
  try {
    // Step 1: Get caption track list from InnerTube player API.
    const tracks = await getCaptionTracks(videoId);
    if (!tracks || tracks.length === 0) return null;

    // Prefer an explicit Spanish track over auto-generated ("asr") ones —
    // manual tracks are more accurate. Fall back to any "es" variant.
    const esTrack =
      tracks.find((t) => t.languageCode === "es" && t.kind !== "asr") ??
      tracks.find((t) => t.languageCode === "es") ??
      tracks.find((t) => t.languageCode?.startsWith("es")) ??
      null;

    if (!esTrack?.baseUrl) return null;

    // Step 2: Fetch the actual caption XML.
    const xml = await fetchCaptionXml(esTrack.baseUrl);
    if (!xml) return null;

    // Step 3: Parse into normalised cues.
    const cues = parseTranscriptXml(xml);

    // AC-1.7: Reject junk or near-empty tracks.
    if (!cues || cues.length < 3) return null;
    const validCues = cues.filter((c) => c.spanish.trim().length >= 2);
    if (validCues.length < 3) return null;

    console.log(`[youtube-client] ${validCues.length} cues fetched for ${videoId}`);
    return validCues.slice(0, MAX_CUES);
  } catch {
    // CORS errors arrive as TypeError: "Failed to fetch".
    // Parse failures, network errors, and unexpected formats also land here.
    // null signals the caller to try the server-side fallback chain.
    return null;
  }
}

// POST to the InnerTube player endpoint — the same call the youtube-transcript
// package makes — to retrieve the list of available caption tracks with their
// download URLs (baseUrl).
async function getCaptionTracks(videoId: string): Promise<CaptionTrack[] | null> {
  const res = await fetch(
    "https://www.youtube.com/youtubei/v1/player?prettyPrint=false",
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        context: {
          client: { clientName: "WEB", clientVersion: "2.20210101" },
        },
        videoId,
      }),
    }
  );

  if (!res.ok) return null;
  const data = await res.json();
  const tracks = data?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
  return Array.isArray(tracks) ? (tracks as CaptionTrack[]) : null;
}

// Fetch the caption XML from a track's baseUrl.
// These URLs point to youtube.com's timedtext API which must support CORS
// so that embedded players on third-party domains can load captions.
async function fetchCaptionXml(baseUrl: string): Promise<string | null> {
  // Only fetch from youtube.com — belt-and-suspenders guard.
  try {
    if (!new URL(baseUrl).hostname.endsWith(".youtube.com")) return null;
  } catch {
    return null;
  }

  const res = await fetch(baseUrl, { cache: "no-store" });
  if (!res.ok) return null;
  return res.text();
}

// Parse the YouTube caption XML into normalised RawCue objects.
// YouTube uses two formats:
//   New: <p t="{ms}" d="{ms}">...</p> with optional <s> word segments
//   Old: <text start="{sec}" dur="{sec}">{text}</text>
function parseTranscriptXml(xml: string): RawCue[] | null {
  const cues: RawCue[] = [];

  // Try new format first
  const P_RE = /<p\s+t="(\d+)"\s+d="(\d+)"[^>]*>([\s\S]*?)<\/p>/g;
  let m: RegExpExecArray | null;

  while ((m = P_RE.exec(xml)) !== null) {
    const tMs = parseInt(m[1], 10);
    const dMs = parseInt(m[2], 10);
    const inner = m[3];

    // Concatenate <s> word segments; fall back to stripping all tags.
    let text = "";
    const S_RE = /<s[^>]*>([^<]*)<\/s>/g;
    let s: RegExpExecArray | null;
    while ((s = S_RE.exec(inner)) !== null) text += s[1];
    if (!text) text = inner.replace(/<[^>]+>/g, "");

    text = decodeEntities(text).trim().replace(/\n/g, " ");
    if (text.length >= 2) {
      cues.push({ start: tMs / 1000, end: (tMs + dMs) / 1000, spanish: text });
    }
  }

  if (cues.length > 0) return normaliseCueEnds(cues);

  // Fall back to old format
  const TEXT_RE = /<text start="([^"]*)" dur="([^"]*)">([^<]*)<\/text>/g;
  while ((m = TEXT_RE.exec(xml)) !== null) {
    const start = parseFloat(m[1]);
    const dur = parseFloat(m[2]);
    const text = decodeEntities(m[3]).trim().replace(/\n/g, " ");
    if (text.length >= 2) {
      cues.push({ start, end: start + dur, spanish: text });
    }
  }

  return cues.length > 0 ? normaliseCueEnds(cues) : null;
}

// Snap each cue's end to the next cue's start so there are no gaps.
function normaliseCueEnds(cues: RawCue[]): RawCue[] {
  return cues.map((c, i) => ({
    ...c,
    end: cues[i + 1]?.start ?? c.end,
  }));
}

function decodeEntities(str: string): string {
  return str
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&#x([0-9a-fA-F]+);/g, (_, hex) =>
      String.fromCodePoint(parseInt(hex, 16))
    )
    .replace(/&#(\d+);/g, (_, dec) =>
      String.fromCodePoint(parseInt(dec, 10))
    );
}
